[package]
name = "ft_fastpath"
version = "0.1.0"
edition = "2021"

[lib]
name = "ft_fastpath"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.21.2", features = ["extension-module", "macros"] }
ignore = "0.4.22"   # gitignore-aware walker
anyhow = "1"
crossbeam-channel = "0.5"
